### ISSUE TITLE
Newer docker versions than 1.10 don't work

### ISSUE THREAD

**Issue by wgm3si** [bosch-ros-pkg/bagbunker#106]
When updating our docker-engine, we can't run commands inside it anymore:
```
rpc error: code = 2 desc = "oci runtime error: exec failed: exit status 1"
```
Last working version: docker-engine=1.10.2-0~trusty

This means we are not able to install our custom jobs anymore.

**Comment by wgm3si** [comment]
I have an update on this -- the problem is caused by Symantec Endpoint Protection:

https://github.com/docker/docker/issues/22705

Solution:
`sudo update-rc.d autoprotect disable`

from https://github.com/docker/docker/issues/15772#issuecomment-142627591

Curiously, with the custom built image this error does not occur...

**Comment by NikolausDemmel** [comment]
@wgm3si should we close this issue then, since it seems to have nothing to do with bagbunker in particular?

**Comment by wgm3si** [comment]
yes, I'll close it...
