### ISSUE TITLE
`bungle-ember build` takes ages to complete

### ISSUE THREAD

**Issue by wgm3si** [bosch-ros-pkg/bagbunker#124]
Following the new readme, I've now been able to do some changes to the frontend using the develop branch. :+1: 
However, rebuilding the page takes 50 seconds, which slows down testing a lot...
```
bagbunker@e3318dc7bd21:/opt/bagbunker-skel-site/frontend$ time bungle-ember build
...
bungle info pipeline Startup complete

real	0m52.577s
user	0m50.865s
sys	0m2.578s
```

**Comment by chaoflow** [comment]
@wgm3si I added a section on [frontend development](https://github.com/bosch-ros-pkg/bagbunker/tree/develop#frontend-development)

Note the `-p` for `bungle-ember@0.4.1`.

**Comment by wgm3si** [comment]
@chaoflow thx!

**Comment by dejanpan** [comment]
did you try? if yes and works => close

**Comment by wgm3si** [comment]
Tried it, works, thanks!
