### ISSUE TITLE
[job] GPS widget plotting GPS trajectory on top of maps

### ISSUE THREAD

**Issue by MatthiasRoland** [bosch-ros-pkg/bagbunker#126]
Is anybody working (or planning to work) on a GPS widget which plots e.g. long / lat trajectories on top of e.g. Open Street Map imagery? We would love to have such a widget and we would also be happy to contribute an implementation of it if somebody can give us some pointers on how to add new widgets to the bagbunker. Cheers!

**Comment by dejanpan** [comment]
close when tested

**Comment by dejanpan** [comment]
@ggaessler pls check it out, it also plots trajectory in color where color denotes the signal quality.

**Comment by ggaessler** [comment]
@dejanpan: Thx for the notification

**Comment by chaoflow** [comment]
branch meanwhile merged
