### ISSUE TITLE
diagnostics job only adds one row for one name

### ISSUE THREAD

**Issue by flixr** [bosch-ros-pkg/bagbunker#78]
We have quite a few diagnostics messages from different nodes (with different names in the message), however only one entry shows up for diagnostics (as opposed to one entry/row for each diagnostic with different name).

**Comment by chaoflow** [comment]
This should be fixed as assumed by @flixr . @dejanpan @flixr could you verify?

**Comment by flixr** [comment]
Yes, this is fixed.
